openapi: 3.0.2
info:
  contact:
    email: jland@redhat.com
    name: Jamie Land
    url: http://redhat.com
  description: Todo List
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: todo
  version: 1.0.0
servers:
- description: Localhost
  url: http://localhost:8080/v1
tags:
- description: 'Todo '
  name: todo
paths:
  /todos:
    description: "The REST endpoint/path used to list and create zero or more `todo`\
      \ entities.  This path contains a `GET` and `POST` operation to perform the\
      \ list and create tasks, respectively."
    get:
      description: Gets a list of all `todo` entities.
      operationId: getTodos
      parameters:
      - description: Show completed/uncompleted todo items
        explode: true
        in: query
        name: completed
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/todo'
                type: array
          description: Successful response - returns an array of `todo` entities.
      summary: List All todos
      tags:
      - todo
      x-accepts: application/json
      x-tags:
      - tag: todo
    post:
      description: Creates a new instance of a `todo`.
      operationId: createTodo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todo'
        description: A new `todo` to be created.
        required: true
      responses:
        "201":
          description: Successful response.
      summary: Create a todo
      tags:
      - todo
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: todo
    summary: Path used to manage the list of todos.
  /todos/{todoId}:
    delete:
      description: Deletes an existing `todo`.
      operationId: deleteTodo
      parameters:
      - description: A unique identifier for a `todo`.
        explode: false
        in: path
        name: todoId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          description: Successful response.
        "404":
          description: Todo item not found
      summary: Delete a todo
      tags:
      - todo
      x-accepts: application/json
      x-tags:
      - tag: todo
    description: "The REST endpoint/path used to get, update, and delete single instances\
      \ of an `todo`.  This path contains `GET`, `PUT`, and `DELETE` operations used\
      \ to perform the get, update, and delete tasks, respectively."
    get:
      description: Gets the details of a single instance of a `todo`.
      operationId: getTodo
      parameters:
      - description: A unique identifier for a `todo`.
        explode: false
        in: path
        name: todoId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todo'
          description: Successful response - returns a single `todo`.
        "404":
          description: Todo item not found
      summary: Get a todo
      tags:
      - todo
      x-accepts: application/json
      x-tags:
      - tag: todo
    put:
      description: Updates an existing `todo`.
      operationId: updateTodo
      parameters:
      - description: A unique identifier for a `todo`.
        explode: false
        in: path
        name: todoId
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/todo'
        description: Updated `todo` information.
        required: true
      responses:
        "202":
          description: Successful response.
        "404":
          description: Todo item not found
      summary: Update a todo
      tags:
      - todo
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: todo
    summary: Path used to manage a single todo.
components:
  schemas:
    todo:
      description: Todo List item
      example:
        value:
          name: Todo item
          description: Description of item
          date: 2018-05-06T18:25:43.511Z
          completed: true
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        date:
          format: date-time
          type: string
        completed:
          description: Is Completed
          type: boolean
      title: Todo
      type: object
